### PR TITLE
Log retries

### PR DESCRIPTION
**Pull request by wraithgar**
Three commits:
- **deps: add proc-log@4.2.0**
- **fix: log errors on retry**
- **chore: fix linting in test files**

Closes https://github.com/npm/cli/issues/7371

### CODE REVIEW

**Comment by wraithgar** [comment]
This technically logs one extra "retrying" because it doesn't know if the retry module is going to actually retry or give up at this point.

**Comment by wraithgar** [comment]
```sh
$ node . view 503 --loglevel verbose --registry=https://httpbin.org/status --fetch-retries=1
npm verbose cli /Users/wraithgar/.nvm/versions/node/v22.0.0/bin/node /Users/wraithgar/Development/npm/cli/branches/gar_fetch-retries
npm info using npm@10.6.0
npm info using node@v22.0.0
npm verbose title npm view 503
npm verbose argv "view" "503" "--loglevel" "verbose" "--registry" "https://httpbin.org/status" "--fetch-retries" "1"
npm verbose logfile logs-max:10 dir:/Users/wraithgar/.npm/_logs/2024-04-30T07_01_18_555Z-
npm verbose logfile /Users/wraithgar/.npm/_logs/2024-04-30T07_01_18_555Z-debug-0.log
npm http fetch GET https://httpbin.org/status/503 failed with 503, retrying
npm http fetch GET https://httpbin.org/status/503 failed with 503, retrying
npm http fetch GET 503 https://httpbin.org/status/503 11203ms attempt #2 (cache skip)
npm verbose stack HttpErrorGeneral: 503 SERVICE UNAVAILABLE - GET https://httpbin.org/status/503
npm verbose stack     at /Users/wraithgar/Development/npm/cli/branches/gar_fetch-retries/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verbose stack     at async RegistryFetcher.packument (/Users/wraithgar/Development/npm/cli/branches/gar_fetch-retries/node_modules/pacote/lib/registry.js:91:19)
npm verbose stack     at async View.getData (/Users/wraithgar/Development/npm/cli/branches/gar_fetch-retries/lib/commands/view.js:193:20)
npm verbose stack     at async View.exec (/Users/wraithgar/Development/npm/cli/branches/gar_fetch-retries/lib/commands/view.js:104:28)
npm verbose stack     at async module.exports (/Users/wraithgar/Development/npm/cli/branches/gar_fetch-retries/lib/cli/entry.js:74:5)
npm verbose statusCode 503
npm verbose pkgid 503@*
npm verbose cwd /Users/wraithgar/Development/npm/cli/branches/gar_fetch-retries
npm verbose Darwin 23.4.0
npm verbose node v22.0.0
npm verbose npm  v10.6.0
npm error code E503
npm error 503 SERVICE UNAVAILABLE - GET https://httpbin.org/status/503
npm verbose exit 1
npm verbose code 1

npm error A complete log of this run can be found in: /Users/wraithgar/.npm/_logs/2024-04-30T07_01_18_555Z-debug-0.log
```

**Review by karenjli — APPROVED** [review]

**Comment by wraithgar** [comment]
Reworded it to just list the retry number if it is a retriable request.

**Review by hashtagchris — APPROVED** [review]
Thank you so much for adding this logging! This will make investigating transient registry errors much easier.

**Pull request merged**
