### PR TITLE
Introduce TypeScript type definitions

### LINKED ISSUE #20: [FEATURE] Open to TypeScript type definitions?
# What / Why
👋 We over at Apollo [just introduced](https://github.com/apollographql/apollo-server/pull/3783) `make-fetch-happen` into our federation gateway and would love to have the TS typings available.

Are the maintainers open to a PR which adds the definitions to the package itself, or would you prefer they end up in `DefinitelyTyped`? At some point, I'll likely do one or the other, with my preference being the former - just wanted to hear your thoughts before I do so.

Thanks!

### PR DESCRIPTION
**Pull request by trevor-scheer**
# What / Why
This PR intends to introduce TypeScript type definitions for this package. Currently Apollo (and other users, based on the 👍 emojis on #20) are really enjoying what `make-fetch-happen` has to offer! For those of us using TypeScript, we're currently [rolling our own](https://github.com/apollographql/apollo-server/pull/4333) and its far from ideal. We recently ran into trouble in doing so as you can see in my linked PR.

I asked the maintainers awhile back (#20) if they'd be willing to accept a PR, but I received no response. I'm hopeful we can land them here, else I'm happy to take them (or someone else can!) over to `DefinitelyTyped`.

I did my best based on the API documentation (which is quite thorough!). But please scrutinize the types which I've imported, as this package depends on libs such as `minipass-fetch` which in turn depends on `node-fetch`. I chose to depend on those types directly rather than copy them over in order to more easily land updates which may come in the future.

Thanks for your consideration!

Fixes #20
cc @abernix

### CODE REVIEW

**Comment by trevor-scheer** [comment]
Follow-up: based on the progress of #23, I've added additional exports to the types (via 8d1e81f). This PR should now be considered blocked by #23. If #23 were to be decided against for some reason, we can revert the commit I've added (8d1e81f).

**Comment by trevor-scheer** [comment]
Hey @isaacs, would you mind taking a look at this please? If you're currently preoccupied with more important work, I'd be happy to take this to `DefinitelyTyped` instead. Thanks!

**Comment by abernix** [comment]
I've gone ahead and opened this on DefinitelyTyped with, I think, a couple improvements inspired mostly by their contribution rules (e.g., recursivity of `defaults()`, tests!): https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50339.  Reviews from qualified reviewers very much welcome!

**Comment by isaacs** [comment]
As a general rule, we don't accept type definitions in PRs because we have no way of ensuring that they don't fall out of sync with the code they describe, short of moving the npm cli to TypeScript, which we have no plans to do at this time.  Until these sorts of PRs come along with a test that ensures that the type definitions are accurate and comprehensive, and can highlight divergence in CI, it is not a good idea to accept them.

**Comment by isaacs** [comment]
As if to prove the point: these types are no longer valid as of mfh version 9.  The `cache` option can only be a string now.

**Pull request closed without merging**
